config/routes.rb
Rails.application.routes.draw do
  resources :gradelists

end

app/models/gradelist.rb
class Gradelist < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gradelists_controller.rb
class GradelistsController < ApplicationController
  before_action :set_gradelist, only: [:show, :edit, :update, :destroy]

  # GET /gradelists
  # GET /gradelists.json
  def index
    @gradelists = Gradelist.all
  end

  # GET /gradelists/1
  # GET /gradelists/1.json
  def show
  end

  # GET /gradelists/new
  def new
    @gradelist = Gradelist.new
  end

  # GET /gradelists/1/edit
  def edit
  end

  # POST /gradelists
  # POST /gradelists.json
  def create
    @gradelist = Gradelist.new(gradelist_params)

    respond_to do |format|
      if @gradelist.save
        format.html { redirect_to @gradelist, notice: 'Gradelist was successfully created.' }
        format.json { render :show, status: :created, location: @gradelist }
      else
        format.html { render :new }
        format.json { render json: @gradelist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gradelists/1
  # PATCH/PUT /gradelists/1.json
  def update
    respond_to do |format|
      if @gradelist.update(gradelist_params)
        format.html { redirect_to @gradelist, notice: 'Gradelist was successfully updated.' }
        format.json { render :show, status: :ok, location: @gradelist }
      else
        format.html { render :edit }
        format.json { render json: @gradelist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gradelists/1
  # DELETE /gradelists/1.json
  def destroy
    @gradelist.destroy
    respond_to do |format|
      format.html { redirect_to gradelists_url, notice: 'Gradelist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gradelist
      @gradelist = Gradelist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gradelist_params
      params.require(:gradelist).permit(:name, :id, :scr)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gradelists_helper.rb
module GradelistsHelper
end

app/views/gradelists/_form.html.erb
<%= form_for(@gradelist) do |f| %>
  <% if @gradelist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gradelist.errors.count, "error") %> prohibited this gradelist from being saved:</h2>

      <ul>
      <% @gradelist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :scr %><br>
    <%= f.number_field :scr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gradelists/edit.html.erb
<h1>Editing gradelist</h1>

<%= render 'form' %>

<%= link_to 'Show', @gradelist %> |
<%= link_to 'Back', gradelists_path %>

app/views/gradelists/index.html.erb
<h1>Listing gradelists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Id</th>
      <th>Scr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gradelists.each do |gradelist| %>
      <tr>
        <td><%= gradelist.name %></td>
        <td><%= gradelist.id %></td>
        <td><%= gradelist.scr %></td>
        <td><%= link_to 'Show', gradelist %></td>
        <td><%= link_to 'Edit', edit_gradelist_path(gradelist) %></td>
        <td><%= link_to 'Destroy', gradelist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gradelist', new_gradelist_path %>

app/views/gradelists/new.html.erb
<h1>New gradelist</h1>

<%= render 'form' %>

<%= link_to 'Back', gradelists_path %>

app/views/gradelists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gradelist.name %>
</p>

<p>
  <strong>Id:</strong>
  <%= @gradelist.id %>
</p>

<p>
  <strong>Scr:</strong>
  <%= @gradelist.scr %>
</p>

<%= link_to 'Edit', edit_gradelist_path(@gradelist) %> |
<%= link_to 'Back', gradelists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grade</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>